### ISSUE TITLE
Registry Updates

### ISSUE THREAD

**Issue by kaandocal** [kaandocal/FiniteStateProjection.jl#3]
@JuliaRegistrator register

**Comment by kaandocal** [comment]
@JuliaRegistrator register

**Comment by kaandocal** [comment]
@JuliaRegistrator register

**Comment by kaandocal** [comment]
@JuliaRegistrator register

**Comment by kaandocal** [comment]
@JuliaRegistrator register

**Comment by kaandocal** [comment]
@JuliaRegistrator register

**Comment by isaacsas** [comment]
@JuliaRegistrator register

**Comment by kaandocal** [comment]
@JuliaRegistrator register

**Comment by kaandocal** [comment]
@JuliaRegistrator register

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register
