### ISSUE TITLE
FiniteStateProjection.jl pinning ArrayInterface at v3.2.2 rendering incompatibility with DifferentialEquations.jl

### ISSUE THREAD

**Issue by sallyseal** [kaandocal/FiniteStateProjection.jl#9]
Hi Kaan

I've just updated to Julia v1.8.0 and when `]add FiniteStateProjection` it pins ArrayInterface.jl at v3.2.2 (instead of the current v6.0.22).  This renders the following packages unable to precompile due to a dependency on ArrayInterface.jl v6.0.22: DifferentialEquations/Sundials/OrdinaryDiffEq/DelayDiffEq/StochasticDiffEq/FindSteadyStates.  See output below.  
Removing all the aforementioned packages (including FiniteStateProjection) and then adding them again (excluding FiniteStateProjection) resolves the issue as it doesn't pin ArrayInterface.jl at v3.2.2.  Thanks!

![Screen Shot 2022-08-24 at 6 36 12 pm](https://user-images.githubusercontent.com/8568276/186371590-4d57ad08-9a05-47ba-811a-697218489cc1.png)

**Comment by kaandocal** [comment]
It seems like this is due to outdated version requirements. The latest version is now online, could you check if that works? Thanks for pointing this out!

**Comment by sallyseal** [comment]
All good - thanks!
